# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Creative TiMe
email: choitm0707@kist.re.kr
description: "Your new default Jekyll theme"
baseurl: "/"  # the subpath of your site, e.g. /blog
url: "https://taemin0707.github.io/"  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Taemin Choi
  twitter: Nope
  picture: 
youtube_username: Taemin0707
twitter_username: Taemin0707
github_username: Taemin0707
logo: /assets/icons/logo.svg
search: true
search_full_content: true
search_provider: lunr

disqus:
  shortname: creative-time

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  lifestory:
    output: true
    permalink: /:collection/:path/

  ideas:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_lifestory"
      type: lifestory
    values:
      layout: post
      read_time: true
  # _ideas
  - scope:
      path: "_ideas"
      type: ideas
    values:
      layout: post
      read_time: true
